services:
  mysql:
    image: mysql:8
    container_name: mysql-8
    environment:
      - 'MYSQL_DATABASE=pedidosEcom'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql